apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-argo-demo
  name: choney-deploy
  #namespace: choney
spec:
  replicas: 3
  selector:
    matchLabels:
      app: choney-deploy
  template:
    metadata:
      labels:
        app: choney-deploy
    spec:
      containers:
      - image: quay.io/gauravkumar9130/nginxdemo
        name: pet
